/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeFunctions */

#ifndef _Included_NativeFunctions
#define _Included_NativeFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeFunctions
 * Method:    addOne
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_NativeFunctions_addOne
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
