/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cloudera_training_hadoop_image_NativeFunctions */

#ifndef _Included_com_cloudera_training_hadoop_image_NativeFunctions
#define _Included_com_cloudera_training_hadoop_image_NativeFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cloudera_training_hadoop_image_NativeFunctions
 * Method:    thumbnailMapper0
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cloudera_training_hadoop_image_NativeFunctions_thumbnailMapper0
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
